{
  "sksl": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec3 color;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    float radius = 2.7999999523162841796875;\n    vec2 uv = FLT_flutter_local_FlutterFragCoord();\n    vec2 center = vec2(radius * 2.0) / vec2(2.0);\n    vec2 uv1 = mod(uv, vec2(2.0, 3.4641015529632568359375) * radius);\n    vec2 uv2 = mod(uv + (vec2(1.0, 1.73205077648162841796875) * radius), vec2(2.0, 3.4641015529632568359375) * radius);\n    float len1 = length(center - uv1);\n    float y1 = 1.0 - smoothstep(radius - 1.60000002384185791015625, radius + 1.60000002384185791015625, len1);\n    float len2 = length(center - uv2);\n    float y2 = 1.0 - smoothstep(radius - 1.60000002384185791015625, radius + 1.60000002384185791015625, len2);\n    float y = max(y1, y2);\n    vec4 color_1 = vec4(color * y, y);\n    fragColor = color_1;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
  "stage": 1,
  "target_platform": 2,
  "uniforms": [
    {
      "array_elements": 0,
      "bit_width": 32,
      "columns": 1,
      "location": 0,
      "name": "color",
      "rows": 3,
      "type": 10
    }
  ]
}